env_name: "walker2d-medium-replay-v2"
max_path_length: 1000

planner_horizon: 8
planner_depth: 2
planner_temperature: 1.0
seed: 0
stride: 1
planner_target_return: 1.0 # Placeholder. Require grid tuning for CFG
planner_w_cfg: 1.0 # Placeholder. Require grid tuning for CG and CFG